// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/nopsky/project-demo/internal/user/entity"
	mock "github.com/stretchr/testify/mock"
)

// IUserService is an autogenerated mock type for the IUserService type
type IUserService struct {
	mock.Mock
}

// RegisterUser provides a mock function with given fields: ctx, _a1
func (_m *IUserService) RegisterUser(ctx context.Context, _a1 *entity.UserEntity) (*entity.UserEntity, error) {
	ret := _m.Called(ctx, _a1)

	var r0 *entity.UserEntity
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserEntity) *entity.UserEntity); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserEntity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entity.UserEntity) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
