// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/nopsky/project-demo/internal/user/repository"
	"github.com/nopsky/project-demo/internal/user/service"
	"github.com/nopsky/project-demo/internal/user/usecase"
	"github.com/nopsky/project-demo/pkg/orm"
)

// Injectors from wire.go:

func MakeUseCase() (*UseCases, error) {
	manager, err := orm.New()
	if err != nil {
		return nil, err
	}
	iUserRepo := repository.NewUserRepo(manager)
	iUserService := service.NewUserService(iUserRepo)
	iUserUseCase := usecase.NewUserUseCase(iUserService)
	useCases := &UseCases{
		UserUseCase: iUserUseCase,
	}
	return useCases, nil
}
