// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *RegisterUserRequest) Validate() error {
	if !(this.CompanyId > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("CompanyId", fmt.Errorf(`value '%v' must be greater than '0'`, this.CompanyId))
	}
	return nil
}
func (this *RegisterUserResponse) Validate() error {
	return nil
}
